const productNames = [
  "Kits antiresaca pillow",
  "KIts antiresaca craft",
  "Vasos personalizados",
  "Tarjetas con bombon",
  "Tarjetas raspadita",
  "Numeros de mesa",
  "Menus",
  "Difusores de auto",
  "KIt de bano",
  "Invitaciones",
  "Invitacion digital classic",
  "Invitacion digital premium",
  "Invitacion digital Black",
  "Invitacion digital 15",
  "Invitacion digital QR",
  "LLavero abridor",
  "Espejitos",
  "Abanicos",
  "Carteles",
  "Bolsitas con bombones",
  "Buzon de regalo",
  "Pulseritas vip",
  "Bolsitas de arroz",
  "Estrellitas",
  "Diarios",
  "Encenderores",
];

export const productOptions = productNames.map((item) => ({
  value: item,
  label: item,
}));
