do $$
begin
  create type public.objetivo_estado as enum ('pendiente', 'en_progreso', 'cumplido');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.pedido_estado as enum ('en_curso', 'enviado', 'entregado');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.consultas (
  id bigint generated by default as identity primary key,
  fecha date not null,
  nombre text not null,
  articulo text not null,
  telefono text not null,
  observaciones text,
  created_at timestamptz not null default now()
);

create table if not exists public.objetivos (
  id bigint generated by default as identity primary key,
  mes text not null check (mes ~ '^\d{4}-\d{2}$'),
  titulo text not null,
  descripcion text not null,
  estado public.objetivo_estado not null default 'pendiente',
  deadline date,
  created_at timestamptz not null default now()
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  cliente_nombre text not null,
  telefono text not null,
  fecha_evento date not null,
  es_envio boolean not null default false,
  estado public.pedido_estado not null default 'en_curso',
  total numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.pedido_items (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  producto_nombre text not null,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12, 2) not null default 0,
  subtotal numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.consultas enable row level security;
alter table public.objetivos enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_items enable row level security;

drop policy if exists "consultas_select_all" on public.consultas;
drop policy if exists "consultas_insert_all" on public.consultas;
drop policy if exists "objetivos_select_all" on public.objetivos;
drop policy if exists "objetivos_insert_all" on public.objetivos;
drop policy if exists "objetivos_update_all" on public.objetivos;
drop policy if exists "pedidos_select_authenticated" on public.pedidos;
drop policy if exists "pedidos_insert_authenticated" on public.pedidos;
drop policy if exists "pedidos_update_authenticated" on public.pedidos;
drop policy if exists "pedido_items_select_authenticated" on public.pedido_items;
drop policy if exists "pedido_items_insert_authenticated" on public.pedido_items;

create policy "consultas_select_authenticated"
on public.consultas
for select
to authenticated
using (true);

create policy "consultas_insert_authenticated"
on public.consultas
for insert
to authenticated
with check (true);

create policy "objetivos_select_authenticated"
on public.objetivos
for select
to authenticated
using (true);

create policy "objetivos_insert_authenticated"
on public.objetivos
for insert
to authenticated
with check (true);

create policy "objetivos_update_authenticated"
on public.objetivos
for update
to authenticated
using (true)
with check (true);

create policy "pedidos_select_authenticated"
on public.pedidos
for select
to authenticated
using (true);

create policy "pedidos_insert_authenticated"
on public.pedidos
for insert
to authenticated
with check (true);

create policy "pedidos_update_authenticated"
on public.pedidos
for update
to authenticated
using (true)
with check (true);

create policy "pedido_items_select_authenticated"
on public.pedido_items
for select
to authenticated
using (true);

create policy "pedido_items_insert_authenticated"
on public.pedido_items
for insert
to authenticated
with check (true);
